import easygopigo3 as go
import time
myRobot = go.EasyGoPiGo3()
myRobot.set_speed(200)
myRobot.forward()
time.sleep(3.3)
myRobot.left()
time.sleep(1.7)
myRobot.forward()
time.sleep(6)
myRobot.right()
time.sleep(1)
myRobot.forward()
time.sleep(3.5)
myRobot.left()
time.sleep(1)
myRobot.forward()
time.sleep(1.5)
myRobot.left()
time.sleep(1.7) # 90 kraadine pööre
myRobot.forward()
time.sleep(11)
myRobot.left()
time.sleep(3)
myRobot.forward()
time.sleep(2)
myRobot.right()
time.sleep(1.7)
myRobot.forward()
time.sleep(1.5)
myrobot.right()
time.sleep(0.4)


myRobot.stop()
